---
title: "Econometrics_Introduction_to_R"
author: "ws"
date: "9/7/2021"
output: html_document
---

#계량경제이론
## Introduction to R

**R 기초 문법, 설정 등등**

```{r setup, include=FALSE}
#show space instead of NA in tables
options(knitr.kable.NA='')

#remove the % lines (that is, comment) in the table generated by xtable::xtable()
options(xtable.comment = FALSE)
```

```{r}
sessionInfo()
getwd()
```

class(), mode(), typeof(): class or mode or type of an object


-typeof() provides the most basic-level classification of an object


```{r}
var1 <- "cool"
var2 <- TRUE
var3 <- NA
var4 <- 1L
var5 <- var1

class(var1)
mode(var1)
typeof(var1)

typeof(var2)
typeof(var3)
typeof(var4)
```


```{r}
# "a" appears in the "values" section of the environment
a <- c(1,2,3)
class(a)
dim(a)
length(a)
b <- c("영희", "철수")
class(b)
dim(b)
length(b)

#transform a sequence of numbers into a 3 x 1 matrix (or a column vector), using as.matrix()
#"a0" appears in the "Data" section of the environment
a0 <- as.matrix(c(1,2,3))
class(a0)
dim(a0)

a1 <- cbind(1,2,3)
class(a1)
dim(a1)

b <- cbind(4,5,6)

# make a matrix using rbind(): row-wise concatenation
c <- rbind(a1, b)
class(c)
dim(c)

#make a matrix by supplying elements and layout, using matrix()
# A is defined as a zero matrix of size 5x5
A <- matrix(0, nrow=5, ncol=5)
A
#1,2,3,4,5 and 6 is reshaped as a matrix with two rows and the numbers fill row by row
B <- matrix(c(1,2,3,4,5,6), nrow=2, byrow=TRUE)
B
B[2,3]
B[2,3] <- 7 #행렬의 2행 3열에 위치한 데이터를 7로 변경 
B

#select an element or elements from a row vector matrix or a column vector matrix
#which effectively has one-dimensional index
d <- cbind(1,2,3)
e <- rbind(1,2,3)
d[2]
e[2]
#matrix operations: element-wise
a1 = cbind(6, 3, 8, 9)
a2 = cbind(9, 1, 3, 5)
a1
a2
a1+a2
a1-a2
a1*a2

#concatenation of strings
#by default, a blank space will be inserted between the two parts
b1 = "Econometrix"
b2 = "1"
paste(b1, b2)
paste(b1, b2, sep="") #띄어쓰기 없음
paste(b1, b2, sep="-") #사이에 '-'문자삽입. 이런식으로 다른 문제 넣을 수 있음
```

```{r}
#matrix operations
#matrix with 4 rows by filling numbers row by row
A <- matrix(c(9,4,12,5,0,7,2,6,8,9,2,9), nrow=4, byrow=TRUE)
A >= 5 #logical operation for each element
A[,2] # 2nd column of A # same as A[,2]
A
t(A) #transpose

B <- matrix(c(9,4,12,5,0,7,2,6,8), nrow=3, byrow=TRUE)
solve(B) #inverse of B
A%*%B #matrix multiplication. A*B 하면 에러
```

```{r}
a <- 4
b <- 5
a > b

#conditional statement
if (a>b) {
  c <- 20
} else {
  c <- 10
}
c #a가 b보다 크면 c를 20으로 지정. 그것이 아니라면 c를 10으로 지정
```

```{r}
#conditional statement (ll): ifelse ([condition], [action1], [action2])
c <- ifelse(a>b, 20, 10)
c

# %% gives the remainder after division operation (called "modulo division" or "modulus)
10 %% 3 #나머지

if(10%%3 ==0){
  print("10 is divisible by 3")
} else if (10 %% 2 == 0){
  print("10 is divisible by 2 but not divisible by 3")
}

# %% gives the integer part after division operation (called "integer division")
45 %% 4
```

```{r}
#looping statement(1): for ([scoping statement]){[action]}
for (i in 1:10){
  print("hellow")
}

result = 0
for (i in 1:100){
  result <- result+i
}
result
```

```{r} 
#looping statement(2): while([conditional statement]){[action]}
result = 0
i = 1
while (i <= 100){
  result <- result+i
  i <- i+1
}
result
```

```{r}
lm
#My Function takes one argument, x, and returns the inverse of its square root
MyFunction <- function(x){
  return(1/sqrt(x))
}
MyFunction(4)

#flexibility of specifying arguments of a function in R
#power =2: default argument
#...: additional argument(s) to be specified when the function is called
MyFunction.power <- function( ..., power = 2 ) {
    temp.v <- MyFunction( ... )
    return( temp.v^power )
}
MyFunction.power( 4 )
MyFunction.power( 4, power=3)

#measure how long an operation takes
system.time(solve(B))
system.time(MyFunction(4))
```

### 2.7. An example: maximum likelihood estimation (MLE)
```{r}


```